apiVersion: apps/v1
kind: Deployment
metadata:
  name: comet
  namespace : milkyway-galaxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: star
  template:
    metadata:
      labels:
        app: star
    spec:
      containers:
      - name: rosetta
        image: busybox
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath : metadata.namespace
        command: ['sh', '-c',  'while true; do echo "{\"name\" : \"rosetta\", \"type\" : \"satellite\", \"planet\" : \"commet\", \"status\" : \"alive\",  \"galaxy\" : \"${namespace}\"}"; sleep 3600; done']
        imagePullPolicy: IfNotPresent

      - name: philae
        image: busybox
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath : metadata.namespace
        command: ['sh', '-c', 'while true; do echo "{\"name\" : \"philae\", \"type\" : \"satellite\", \"planet\" : \"commet\", \"status\" : \"alive\",  \"galaxy\" : \"${namespace}\"}"; sleep 3600; done']
        imagePullPolicy: IfNotPresent