###
  # Pod with Multiple container
  # pod describing earth with launched satellites (sputnik1 and aura) as its container
###
apiVersion: v1
kind: Pod
metadata:
  name: earth
  namespace: milkyway-galaxy
spec:
  containers:
  # container 1 for sputnik satellite
  - name: sputnik-1
    image: busybox
    ports:
    - containerPort: 80
    env:
    - name: namespace
      valueFrom:
        fieldRef:
          fieldPath : metadata.namespace
    command: ['sh', '-c', 'while true; do echo "{\"name\" : \"sputnik-1\", \"type\" : \"satellite\", \"planet\" : \"earth\", \"status\" : \"alive\",  \"galaxy\" : \"${namespace}\"}"; sleep 3600; done']
    imagePullPolicy: IfNotPresent
  # container 2 for aura satellite
  - name: aura
    image: busybox
    ports:
    - containerPort : 90
    env:
    - name: namespace
      valueFrom:
          fieldRef:
              fieldPath: metadata.namespace
    command: ['sh', '-c', 'while true; do echo "{\"name\" : \"Aura\", \"type\" : \"satellite\", \"planet\" : \"earth\", \"status\" : \"alive\",  \"galaxy\" : \"${namespace}\"}"; sleep 3600; done']
    imagePullPolicy: IfNotPresent
    