# Default values for milkyway-galaxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

configs:
  isSatellitesAllowed: "true",
  isResearchable: "true",
  isLivelinessExposable: "true"