apiVersion: v1
kind: ConfigMap
metadata:
  name: milkyway-galaxy-configs
  namespace: milkyway-galaxy
  labels:
    app: galaxy
data:
  ## Mounting key values as Env variables
  name: "milkyway-galaxy"
  type: "galaxy"
  starsCount: "100"
  accessible: "true"
  ## Mounting entire contents as files
  configs: |-
    {
      "isSatellitesAllowed" : "{{.Values.config.isSatellitesAllowed}}",
      "isResearchable" : "{{.Values.config.isResearchable}}",
      "isLivelinessExposable" : "{{.Values.config.isLivelinessExposable}}"
    }

